INSERT INTO TB_FEATURE(ID, CODE, ICON, DESCRIPTION) VALUES(1, 'FT-001', 'feature_icon_01', 'PIX')
INSERT INTO TB_FEATURE(ID, CODE, ICON, DESCRIPTION) VALUES(2, 'FT-002', 'feature_icon_02', 'Boleto')
INSERT INTO TB_FEATURE(ID, CODE, ICON, DESCRIPTION) VALUES(3, 'FT-003', 'feature_icon_03', 'Consorcio')
INSERT INTO TB_FEATURE(ID, CODE, ICON, DESCRIPTION) VALUES(4, 'FT-004', 'feature_icon_04', 'Investimentos')
INSERT INTO TB_FEATURE(ID, CODE, ICON, DESCRIPTION) VALUES(5, 'FT-005', 'feature_icon_05', 'Open Finance')

INSERT INTO TB_NEWS(ID, CODE, ICON, DESCRIPTION) VALUES(1, 'NW-001', 'news_icon_01', 'Titulo de Capitalizacao DinDin')
INSERT INTO TB_NEWS(ID, CODE, ICON, DESCRIPTION) VALUES(2, 'NW-002', 'news_icon_02', 'Novo cartao disponivel')
INSERT INTO TB_NEWS(ID, CODE, ICON, DESCRIPTION) VALUES(3, 'NW-003', 'news_icon_03', 'Faca investimentos com a gente')
INSERT INTO TB_NEWS(ID, CODE, ICON, DESCRIPTION) VALUES(4, 'NW-004', 'news_icon_04', 'Pontos disponiveis no Esfera')
INSERT INTO TB_NEWS(ID, CODE, ICON, DESCRIPTION) VALUES(5, 'NW-005', 'news_icon_05', 'Mantenha suas chaves com a gente e ganhe descontos')